# Site settings
author: Zach Durr
title: My First Gem
header-img: img/home-bg.png
email: zdurr22@gmail.com
copyright_name: Zach Durr
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Portfolio Project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zdurr22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
